services:
  mongodb:
       image: mongo
       ports:
         - "27017:27017"
       environment:
         - MONGO_INITDB_ROOT_USERNAME=admin
         - MONGO_INITDB_ROOT_PASSWORD=password
       networks:
         - health-monitoring-app-network
       volumes:
         - ./mongo-init:/docker-entrypoint-initdb.d  # Mount the init script


  mongo-express:
    image: mongo-express:0.54.0  # Use a specific version
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - health-monitoring-app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - health-monitoring-app-network

  frontend:
    build:
      context: ./tsyp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - health-monitoring-app-network

networks:
  health-monitoring-app-network:
    driver: bridge